### ISSUE TITLE
Сделать краулер для каналов и чатов Telegram

### ISSUE THREAD

**Issue by ivbeg** [ruarxive/ruarxive-research#1]
### Задача минимум
Утилита командной строки собирающая все публикации из телеграм каналов по списку и сохраняющая в JSONL формате, желательно, сразу со сжатием в Gzip или Zip или lz4

По аналогии с утилитами twarc - https://github.com/DocNow/twarc для Twitter'а и Instaloader для Instagram https://instaloader.github.io.

Основные команды:
* **configure** - настроить ключи подключения или логин и пароль, с сохранением параметров в директории пользователя в виде файла .tgarc или аналога (tgarc сокращение от Telegram Archive)
* **save** - сохранение выбранного чата или канала в телеграм или группы чатов и каналов по их имени или по ссылкам. 

Команда **save** должна обрабатывать следующие опции:
* **--no-video** - не выгружать видео медиа-файлы
* **--no-pictures** - не выгружать фотографии
* **--no-files** - не выгружать остальные типы файлов (не видео и не фотографии)
* **--max-size <размер файла в МБ>** - максимальный размер одного выгружаемого файла
* **--update** - обновить ранее выгруженные данные
* **--format <csv/json>** - формат сохранения сообщений CSV или JSON(l) формат.
* **--input <filename>** - файл со списком названий чатов и каналов или ссылок на них если у них нет названия и они приватные.
* **--filter-text <регулярное выражение>** - фильтрация выгружаемых сообщений по через регулярное выражение по его тексту (не обязательно в первой версии.
* **--output/-o <папка>** - путь для сохранения файлов и данных, если не задан то автоматически создавать папку tgarc-<датазапуска>

### Задача максимум
Сделать краулер который в непрервном режиме вел бы архивацию всех публикаций с сохранением в СУБД, MongoDB или ArangoDB в каналах по списку, для некоторых каналов с возможностью архивации и всех опубликованных в них файлов.

**Comment by runiner** [comment]
опция --max-size - это про итоговый файл архива, или про предельный размер для каждого из выгружаемых файлов в канале?

**Comment by ivbeg** [comment]
@runiner это предельный размер одного файла.

**Comment by AduchiMergen** [comment]
какой формат для json, для csv ?

сообщение от телеграма:

`
{
    "_": "Message",
    "message_id": 1,
    "sender_chat": {
        "_": "Chat",
        "id": -1001292933413,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "Pyrogram News",
        "username": "pyrogram",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAAT45WgGwAEAgAD21ZK3hb___9BZBxmuSO5seRqCQABHgQ",
            "small_photo_unique_id": "AQAD45WgGwAE5GoJAAE",
            "big_file_id": "AQADBAAT45WgGwAEAwAD21ZK3hb___9BZBxmuSO5seZqCQABHgQ",
            "big_photo_unique_id": "AQAD45WgGwAE5moJAAE"
        },
        "dc_id": 4
    },
    "date": "2018-02-26 02:50:45",
    "chat": {
        "_": "Chat",
        "id": -1001292933413,
        "type": "channel",
        "is_verified": false,
        "is_restricted": false,
        "is_creator": false,
        "is_scam": false,
        "is_fake": false,
        "title": "Pyrogram News",
        "username": "pyrogram",
        "photo": {
            "_": "ChatPhoto",
            "small_file_id": "AQADBAAT45WgGwAEAgAD21ZK3hb___9BZBxmuSO5seRqCQABHgQ",
            "small_photo_unique_id": "AQAD45WgGwAE5GoJAAE",
            "big_file_id": "AQADBAAT45WgGwAEAwAD21ZK3hb___9BZBxmuSO5seZqCQABHgQ",
            "big_photo_unique_id": "AQAD45WgGwAE5moJAAE"
        },
        "dc_id": 4
    },
    "service": true,
    "channel_chat_created": true
}
`

**Comment by ivbeg** [comment]
@AduchiMergen для JSON как есть, лучше упакованные в JSONlines как построчный JSON
В csv он также преобразуется легко, там нет массивов, вот такие выйдут заголовки у CSV
_
message_id
sender_chat._
sender_chat.id
sender_chat.type
sender_chat.is_verified
sender_chat.is_restricted
sender_chat.is_creator
sender_chat.is_scam
sender_chat.is_fake
sender_chat.title
sender_chat.username
sender_chat.photo._
sender_chat.photo.small_file_id
sender_chat.photo.small_photo_unique_id
sender_chat.photo.big_file_id
sender_chat.photo.big_photo_unique_id
sender_chat.dc_id
date
chat._
chat.id
chat.type
chat.is_verified
chat.is_restricted
chat.is_creator
chat.is_scam
chat.is_fake
chat.title
chat.username
chat.photo._
chat.photo.small_file_id
chat.photo.small_photo_unique_id
chat.photo.big_file_id
chat.photo.big_photo_unique_id
chat.dc_id
service
channel_chat_created

**Comment by AduchiMergen** [comment]
Первый подход: https://github.com/AduchiMergen/tgarc
буду благодарен обратной связи

**Comment by ivbeg** [comment]
@AduchiMergen спасибо! В ближайшее время посмотрю
